'use strict';
const C=window.SHOP_CONFIG;
const PRODUCTS=[
 ['perilla','紫蘇葉純露',400,'草本氣味，為日常空間添一點植物氣息。'],
 ['thyme','沉香醇百里香純露',395,'溫和草本調，適合喜歡清新植物香氣的你。'],
 ['cistus','岩玫瑰純露',420,'感受岩玫瑰的植物氣息，享受片刻停頓。'],
 ['rhododendron','髯花杜鵑純露',500,'植物香氣陪伴日常，也適合安靜獨處的時刻。'],
 ['scalp','飽護頭皮純露',480,'頭皮保養配方，使用方式請依產品標示。'],
 ['inula','土木香純露',450,'認識土木香的氣味，為空間增添草本風景。'],
 ['chamomile','羅馬洋甘菊純露',450,'細緻的植物氣息，陪你放慢日常步調。'],
 ['bath','安久寶寶精油泡澡露',400,'100ml｜累計滿 10 瓶成團。適用年齡與特殊體質請先向供應商確認。']
].map(([id,name,price,description])=>({id,name,price,description}));
const ORIGINAL_KEYWORDS={perilla:'免疫力、脾胃',thyme:'免疫力、抗病毒',cistus:'抗病毒、止血、抗發炎、鼻塞、洗鼻子',rhododendron:'免疫力、止痛、消炎、滋補神經、收斂黏液、冥想',scalp:'止癢、蓬鬆、滋養',inula:'止咳、化解黏液、止痛、鼻塞',chamomile:'止痛、修護、鎮靜、脹氣、紅屁屁',bath:'私密處、修護、泡澡、免疫力'};
const cart={};let order=null;
const $=s=>document.querySelector(s),money=n=>'NT$'+n.toLocaleString('zh-TW');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2500)}
async function copy(s){try{await navigator.clipboard.writeText(s);toast('已複製')}catch{const t=document.createElement('textarea');t.value=s;document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();toast(ok?'已複製':'請長按文字手動複製')}}
$('#products').innerHTML=PRODUCTS.map((p,i)=>`<article class="product"><span class="number">BOTANICAL / ${String(i+1).padStart(2,'0')}</span><h3>${p.name}</h3><span class="size">${p.id==='bath'?'100ml · 10 瓶成團':'250ml · 冷藏保存'}</span><p>${p.description}</p><details><summary>查看商品資訊</summary><p>保存期限：${p.id==='bath'?'常溫 12 個月':'冷藏 6 個月'}，開封後請盡速使用完畢。${p.id==='scalp'?'成分：依蘭依蘭、廣霍香、大西洋雪松、迷迭香、維吉尼亞雪松、羅馬洋甘菊。':''}</p></details><details class="original"><summary>原始資料關鍵字</summary><p>${ORIGINAL_KEYWORDS[p.id]}</p><p class="small">以上保留原始資料用語，功效未經本頁核實，不能視為本品已證實的醫療效果或使用指示。請勿以本品治療疾病或用於洗鼻。</p></details><div class="price">${money(p.price)}</div><button class="secondary" data-add="${p.id}">加入購物車</button></article>`).join('');
$('#products').addEventListener('click',e=>{const id=e.target.dataset.add;if(id){cart[id]=Math.min(99,(cart[id]||0)+1);render();toast('已加入購物車')}});
function subtotal(){return PRODUCTS.reduce((n,p)=>n+p.price*(cart[p.id]||0),0)}
function shipping(){return C.shipping[$('#orderForm').elements.delivery.value]}
function render(){const items=PRODUCTS.filter(p=>cart[p.id]);$('#count').textContent=items.reduce((n,p)=>n+cart[p.id],0);$('#cart').innerHTML=items.length?items.map(p=>`<div class="cart-row"><div class="cart-top"><span>${p.name}</span><b>${money(p.price*cart[p.id])}</b></div><div class="qty"><button type="button" data-id="${p.id}" data-delta="-1" aria-label="減少${p.name}">−</button><span>${cart[p.id]}</span><button type="button" data-id="${p.id}" data-delta="1" aria-label="增加${p.name}">＋</button><button class="remove" type="button" data-id="${p.id}" data-delta="remove">移除</button></div></div>`).join(''):'<p>購物車還沒有商品。<br>先選一瓶喜歡的植物氣息吧。</p>';$('#subtotal').textContent=money(subtotal());$('#shipping').textContent=Number.isInteger(shipping())?money(shipping()):'運費尚未設定';$('#total').textContent=Number.isInteger(shipping())?money(subtotal()+shipping()):'待確認運費'}
$('#cart').addEventListener('click',e=>{const {id,delta}=e.target.dataset;if(!id)return;cart[id]=delta==='remove'?0:Math.min(99,Math.max(0,cart[id]+Number(delta)));render()});
const f=$('#orderForm');f.elements.delivery.forEach(r=>r.addEventListener('change',()=>{const home=f.elements.delivery.value==='home';$('#homeFields').hidden=!home;$('#familyFields').hidden=home;['postal','address'].forEach(n=>{f.elements[n].disabled=!home;f.elements[n].required=home});f.elements.store.disabled=home;f.elements.store.required=!home;render()}));
$('#same').onclick=()=>{f.elements.recipient.value=f.elements.buyer.value;f.elements.recipientPhone.value=f.elements.phone.value};
function rpc(payload){return new Promise((resolve,reject)=>{const token=crypto.randomUUID(),frame=document.createElement('iframe'),form=document.createElement('form');frame.name='order_'+token;frame.hidden=true;form.method='POST';form.action=C.scriptUrl;form.target=frame.name;form.hidden=true;const input=document.createElement('input');input.name='payload';input.value=JSON.stringify({...payload,token});form.append(input);let timer;const clean=()=>{clearTimeout(timer);window.removeEventListener('message',listener);form.remove();frame.remove()};const listener=e=>{if(!/^https:\/\/([a-z0-9-]+\.)*(script.google.com|googleusercontent.com)$/.test(e.origin)||!e.data||e.data.token!==token)return;clean();e.data.ok?resolve(e.data):reject(new Error(e.data.error||'送出失敗'))};window.addEventListener('message',listener);document.body.append(frame,form);timer=setTimeout(()=>{clean();reject(new Error('未收到訂單確認。請重試；同一筆訂單不會重複建立。'))},60000);form.submit()})}
let pendingId=null,pendingPayload=null;
f.addEventListener('submit',async e=>{e.preventDefault();if(!subtotal())return toast('請先加入商品');if(!C.scriptUrl||!C.lineUrl||!Number.isInteger(shipping())){$('#formStatus').textContent='團購尚未開放結帳，請主辦人完成訂單、LINE 與運費設定。';return}const b=$('#submit');b.disabled=true;$('#formStatus').textContent='正在建立訂單，請稍候…';try{pendingId ||= crypto.randomUUID();if(!pendingPayload){const data=Object.fromEntries(new FormData(f));pendingPayload={action:'order',requestId:pendingId,...data,items:PRODUCTS.filter(p=>cart[p.id]).map(p=>({id:p.id,qty:cart[p.id]}))};f.querySelectorAll('input,button').forEach(x=>x.disabled=true);$('#products').querySelectorAll('button').forEach(x=>x.disabled=true);$('#cart').querySelectorAll('button').forEach(x=>x.disabled=true);}const result=await rpc(pendingPayload);order=result;$('#orderInfo').textContent=`訂單 ${result.orderId}｜應付 ${money(result.total)}。${result.emailSent?'訂購明細已寄出。':'訂單已建立，確認信暫未寄出，請向官方 LINE 索取明細。'}`;$('#payment').hidden=false;$('#reportForm').elements.paid.value=result.total;$('#formStatus').textContent='訂單已建立，請往下完成付款。';f.querySelectorAll('input,button').forEach(x=>x.disabled=true);$('#payment').scrollIntoView({behavior:'smooth'});}catch(err){$('#formStatus').textContent=err.message;b.disabled=false}});
$('#copyBank').onclick=()=>copy(C.bankAccount);
if(C.linePayQr){$('#qr').src=C.linePayQr;$('#qr').hidden=false;$('#qrMissing').hidden=true;$('#qr').onerror=()=>{$('#qr').hidden=true;$('#qrMissing').hidden=false;$('#linepayOption').disabled=true}}else $('#linepayOption').disabled=true;
const rf=$('#reportForm');rf.elements.method.forEach(r=>r.onchange=()=>{const bank=rf.elements.method.value==='bank';$('#last5Label').hidden=!bank;rf.elements.last5.disabled=!bank;$('#payRefLabel').hidden=bank;rf.elements.payRef.disabled=bank});
rf.onsubmit=async e=>{e.preventDefault();if(!order)return;$('#reportButton').disabled=true;$('#reportStatus').textContent='正在儲存付款回報…';try{const data=Object.fromEntries(new FormData(rf));await rpc({action:'payment',requestId:pendingId,orderId:order.orderId,...data});const msg=`團購付款回報\n訂單編號：${order.orderId}\n訂購人：${pendingPayload.buyer}\n付款金額：NT$${data.paid}\n${data.method==='bank'?'匯款後五碼：'+data.last5:'LINE Pay 交易編號：'+data.payRef}`;$('#reportText').value=msg;$('#lineActions').hidden=false;$('#openLine').href=C.lineUrl;$('#reportStatus').textContent='付款回報已記錄，請複製下方內容並貼到官方 LINE。';await copy(msg)}catch(err){$('#reportStatus').textContent=err.message}finally{$('#reportButton').disabled=false}};
$('#copyReport').onclick=()=>copy($('#reportText').value);
render();
