/** 只貼到 Google Apps Script；SPREADSHEET_ID 在指令碼屬性設定。 */
const PRICES={perilla:400,thyme:395,cistus:420,rhododendron:500,scalp:480,inula:450,chamomile:450,bath:400};
const NAMES={perilla:'紫蘇葉純露 250ml',thyme:'沉香醇百里香純露 250ml',cistus:'岩玫瑰純露 250ml',rhododendron:'髯花杜鵑純露 250ml',scalp:'飽護頭皮純露 250ml',inula:'土木香純露 250ml',chamomile:'羅馬洋甘菊純露 250ml',bath:'安久寶寶精油泡澡露 100ml'};
const HEADERS=['建立時間','訂單編號','請求識別碼','訂購人','Email','手機','收件人','收件人電話','配送方式','郵遞區號','地址','全家店名','商品明細','商品小計','運費','應付金額','付款方式','實付金額','後五碼','LINE Pay交易編號','付款回報時間','付款狀態','確認信狀態'];
function sheet_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(!id)throw Error('主辦人尚未完成後台設定');const book=SpreadsheetApp.openById(id);let s=book.getSheetByName('訂單');if(!s){s=book.insertSheet('訂單');s.appendRow(HEADERS);s.setFrozenRows(1);}return s;}
function safe_(v){const s=String(v||'');return /^[=+\-@]/.test(s)?"'"+s:s;}
function text_(v,max){if(typeof v!=='string'||!v.trim()||v.length>max)throw Error('資料格式不正確，請檢查必填欄位');return v.trim();}
function doPost(e){let p={},result;const lock=LockService.getScriptLock();try{p=JSON.parse(e.parameter.payload||'{}');if(!/^[a-f0-9-]{36}$/.test(p.requestId||''))throw Error('訂单識別碼不正確');lock.waitLock(20000);result=p.action==='order'?createOrder_(p):p.action==='payment'?payment_(p):(()=>{throw Error('無效操作')})();result.ok=true;}catch(err){console.error(err);result={ok:false,error:String(err.message||'處理失敗')};}finally{if(lock.hasLock())lock.releaseLock();}result.token=p.token;const json=JSON.stringify(result).replace(/</g,'\\u003c');return HtmlService.createHtmlOutput('<script>window.top.postMessage('+json+',"*");</script>').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
function createOrder_(p){const s=sheet_(),rows=s.getDataRange().getValues();const existing=rows.findIndex((r,i)=>i>0&&r[2]===p.requestId);if(existing>0){const r=rows[existing];return {orderId:r[1],total:r[15],emailSent:r[22]==='已寄出'};}
const buyer=text_(p.buyer,60),email=text_(p.email,150),phone=text_(p.phone,10),recipient=text_(p.recipient,60),recipientPhone=text_(p.recipientPhone,10);
if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!/^09\d{8}$/.test(phone)||!/^09\d{8}$/.test(recipientPhone))throw Error('請檢查 Email 與手機格式');
if(!['home','family'].includes(p.delivery))throw Error('請選擇配送方式');let postal='',address='',store='';if(p.delivery==='home'){postal=text_(p.postal,6);if(!/^\d{3}(\d{2,3})?$/.test(postal))throw Error('郵遞區號格式錯誤');address=text_(p.address,250);}else store=text_(p.store,100);
const props=PropertiesService.getScriptProperties(),raw=props.getProperty(p.delivery==='home'?'SHIPPING_HOME':'SHIPPING_FAMILY');if(raw!==null&&!/^\d+$/.test(raw))throw Error('主辦人尚未設定運費');const shipping=raw===null?(p.delivery==='home'?65:60):Number(raw);
if(!Array.isArray(p.items)||!p.items.length||p.items.length>8)throw Error('購物車內容錯誤');let subtotal=0;const seen={},items=p.items.map(i=>{if(!Object.prototype.hasOwnProperty.call(PRICES,i.id)||seen[i.id]||!Number.isInteger(i.qty)||i.qty<1||i.qty>99)throw Error('商品或數量錯誤');seen[i.id]=true;subtotal+=PRICES[i.id]*i.qty;return {id:i.id,name:NAMES[i.id],qty:i.qty,price:PRICES[i.id]};});const total=subtotal+shipping;
const orderId='CK'+Utilities.formatDate(new Date(),'Asia/Taipei','yyMMddHHmmss')+Utilities.getUuid().slice(0,6).toUpperCase();const detail=items.map(i=>i.name+' × '+i.qty+' = NT$'+i.price*i.qty).join('\n');
const row=[new Date(),orderId,p.requestId,buyer,email,phone,recipient,recipientPhone,p.delivery==='home'?'宅配':'全家超取',postal,address,store,detail,subtotal,shipping,total,'','','','','','待付款','待寄送'];const rowNo=s.getLastRow()+1;[4,5,6,7,8,10,11,12,13].forEach(c=>s.getRange(rowNo,c).setNumberFormat('@'));s.getRange(rowNo,1,1,row.length).setValues([row.map(v=>typeof v==='string'?safe_(v):v)]);
let emailSent=false;try{MailApp.sendEmail({to:email,subject:'CHIKAIMA 團購訂購明細｜'+orderId,body:'親愛的 '+buyer+'：\n\n已收到你的訂單。\n訂單編號：'+orderId+'\n\n'+detail+'\n\n商品小計：NT$'+subtotal+'\n運費：NT$'+shipping+'\n應付金額：NT$'+total+'\n\n收件人：'+recipient+'\n收件人電話：'+recipientPhone+'\n配送：'+(p.delivery==='home'?postal+' '+address:'全家 '+store)+'\n\n匯款：郵局 700\n帳號：00415700152886\n戶名：張家馨\n付款後請在訂購頁填寫付款回報，並複製至官方 LINE 送出。\n\n泡澡露滿 10 瓶成團，成團、出貨及未成團退款安排將另行通知。\n此信確認訂單成立，付款仍需人工核對。',name:'CHIKAIMA'});emailSent=true;s.getRange(rowNo,23).setValue('已寄出');}catch(err){s.getRange(rowNo,23).setValue('寄送失敗，請人工補寄');console.error(err);}return {orderId,total,emailSent};}
function payment_(p){const s=sheet_(),rows=s.getDataRange().getValues();const i=rows.findIndex((r,j)=>j>0&&r[2]===p.requestId&&r[1]===p.orderId);if(i<1)throw Error('找不到訂單');if(!['bank','linepay'].includes(p.method))throw Error('付款方式錯誤');const paid=Number(p.paid);if(!Number.isInteger(paid)||paid<1||paid>10000000)throw Error('付款金額錯誤');let last5='',ref='';if(p.method==='bank'){last5=text_(p.last5,5);if(!/^\d{5}$/.test(last5))throw Error('後五碼格式錯誤');}else ref=text_(p.payRef,100);s.getRange(i+1,19,1,2).setNumberFormat('@');s.getRange(i+1,17,1,6).setValues([[p.method==='bank'?'銀行匯款':'LINE Pay',paid,safe_(last5),safe_(ref),new Date(),'已回報，待核對']]);s.getRange(i+1,19).setNumberFormat('@');return {orderId:p.orderId};}
// 編輯器手動執行一次，建立訂單工作表並授權試算表與寄信權限。
function setup(){sheet_();MailApp.getRemainingDailyQuota();}
